id: process_entwine
namespace: local

tasks:
  - id: download_from_minio
    type: io.kestra.plugin.core.http.Download
    uri: http://minio:9000/input-bucket/simple.laz
    headers:
      Authorization: Basic {{ "minioadmin:minioadmin" | base64_encode }}

  - id: compute_hash
    type: io.kestra.plugin.scripts.shell.Script
    outputFiles:
      - /output/simple.laz.sha256
    script: |
      echo "The current execution is: {{ execution.id }}"

      # Install required packages
      apk add --no-cache curl bash coreutils

      # Compute SHA256 hash of the downloaded file
      sha256sum {{ outputs.download_from_minio.uri }} > /output/simple.laz.sha256

    runner: DOCKER
    docker:
      image: alpine:latest
      volumes:
        - name: entwine-output
          path: /output

triggers:
  - id: watch_minio
    type: io.kestra.plugin.minio.Trigger
    endpoint: http://minio:9000
    bucket: "input-bucket"
    accessKeyId: "minioadmin"
    secretKeyId: "minioadmin"
    interval: "PT1M"
    action: NONE
