id: process_entwine
namespace: local

tasks:
  - id: download_from_minio
    type: io.kestra.plugin.minio.Download
    accessKeyId: "minioadmin"
    secretKeyId: "minioadmin"
    endpoint: "http://minio:9000"
    bucket: "input-bucket"
    key: "simple.laz"

  - id: compute_hash
    type: io.kestra.plugin.scripts.shell.Script
    outputFiles:
      - /output/simple.laz.sha256
    script: |
      echo "The current execution is: {{ execution.id }}"

      # Ensure the output directory exists
      mkdir -p /output

      # Compute SHA256 hash of the downloaded file and display it
      sha256sum {{ outputs.download_from_minio.uri }} | tee /output/simple.laz.sha256

triggers:
  - id: watch_minio
    type: io.kestra.plugin.minio.Trigger
    endpoint: http://minio:9000
    bucket: "input-bucket"
    accessKeyId: "minioadmin"
    secretKeyId: "minioadmin"
    interval: "PT1M"
    action: NONE
