---
# Define common labels for Docker objects.
x-labels: &labels
  labels:
    # Name of the application, set using the Compose project name.
    app.name: ${COMPOSE_PROJECT_NAME}

services:
  registry:
    image: ${COMPOSE_PROJECT_NAME}/${REGISTRY_IMAGE_NAME}:${REGISTRY_IMAGE_TAG}
    hostname: ${COMPOSE_PROJECT_NAME}.${REGISTRY_HOSTNAME}
    container_name: ${COMPOSE_PROJECT_NAME}-${REGISTRY_HOSTNAME}
    restart: unless-stopped
    build:
      context: .
      dockerfile: registry.Dockerfile
      args:
        - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
        - REGISTRY_PORT=${REGISTRY_PORT}
        - BASE_IMAGE_ID=${BASE_IMAGE_ID}
      x-bake:
        platforms: "${DOCKER_DEFAULT_PLATFORM}"
        output: type=docker
    ports:
      - "${REGISTRY_EXPOSED_PORT}:${REGISTRY_PORT}"
    networks:
      default:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.${REGISTRY_HOSTNAME}
    env_file:
      - registry.env
    volumes:
      # - ./config/config.yml:/etc/docker/registry/config.yml:ro
      - ./data:/var/lib/registry:rw
