---
# Define common labels for Docker objects.
x-labels: &labels
  labels:
    # Name of the application, set using the Compose project name.
    app.name: ${COMPOSE_PROJECT_NAME}

services:
  matchering:
    extends:
      file: ../common.yml
      service: common
    image: ${COMPOSE_PROJECT_NAME}/${MATCHERING_IMAGE_NAME}:${MATCHERING_IMAGE_TAG}
    hostname: ${COMPOSE_PROJECT_NAME}.${MATCHERING_HOSTNAME}
    container_name: ${COMPOSE_PROJECT_NAME}-${MATCHERING_HOSTNAME}
    build:
      context: .
      dockerfile: matchering.Dockerfile
      target: final
      args:
        - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
        - BASE_IMAGE_NAME=${BASE_IMAGE_NAME}
        - BASE_IMAGE_VERSION=${BASE_IMAGE_VERSION}
        - MATCHERING_PORT=${MATCHERING_PORT}
        - BASE_IMAGE_ID=${BASE_IMAGE_ID:-sha256:0}
      x-bake:
        platforms: "${DOCKER_DEFAULT_PLATFORM}"
        output: type=image,name=localhost:5005/${COMPOSE_PROJECT_NAME}/${BASE_IMAGE_NAME}:${BASE_IMAGE_VERSION},push=true,registry.insecure=true
    ports:
      - "${MATCHERING_EXPOSED_PORT}:${MATCHERING_PORT}"
    networks:
      default:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.${MATCHERING_HOSTNAME}
    env_file:
      - matchering.env

# volumes:
#   matchering_data:
#     name: ${MATCHERING_DATA_VOLUME}
#     driver: local
#     <<: [*labels]
