' ***********************************************************************
'  File: architecture.puml
'  Purpose: Combines and includes all the modular components of the system 
'           architecture without connecting them yet.
'  Usage: This file is the main architecture diagram, serving as a base 
'         for further connections and interactions between components.
'  Author: Alan Szmyt
' ***********************************************************************

@startuml "System Architecture"
!include data_lake.puml
!include sql_query_engine.puml
!include blob_storage.puml
!include job_orchestrator.puml
!include data_hub.puml
!include client_applications.puml

@startuml
!include objects/node_with_logo.puml

!$show_icons = "true"
$node_with_logo("Job Orchestrator", "airflow", "Handles ETL processes")
@enduml

@enduml
